### ISSUE TITLE
dyld: Library not loaded: @rpath/ForeSee.framework/ForeSee

### ISSUE THREAD

**Issue by chrisballinger** [foreseecode/foresee-sdk-ios-samples#12]
On the latest develop branch `72d501bde11e442934391dee55d09a79dec70951` I cannot run the examples, even after running `pod install`.

```
dyld: Library not loaded: @rpath/ForeSee.framework/ForeSee
  Referenced from: /Users/chrisbal/Library/Developer/CoreSimulator/Devices/8FAE80C7-CE04-4F4A-BD4C-95EAB508C733/data/Containers/Bundle/Application/FBC926AF-540F-4AB1-8E2D-7FEEA3FC77E7/BasicSample.app/BasicSample
  Reason: image not found
```

Nothing funky seems to be happening with the rpath settings, not sure what's wrong here.

**Comment by rreballos** [comment]
+1, all the examples are useless

**Comment by lwburk** [comment]
Despite what [CocoaPods says about the utility of checking-in the `Pods` directory](https://guides.cocoapods.org/using/using-cocoapods#benefits-of-checking-in-the-pods-directory), it seems to be causing issues with the latest versions of Xcode.

Please try the following:

    $ sudo rm -r Pods/
    $ pod install

This will create a fresh install of the pods using the versions specified in the `Podfile.lock`. 

Let me know if this helps!

**Comment by wayneburkett** [comment]
Fixed
