### ISSUE TITLE
6.0.5 invalid for App Store submission due to embedded Swift libraries

### ISSUE THREAD

**Issue by jshier** [foreseecode/foresee-sdk-ios-samples#84]
Seems the 6.0.5 release embeds the Swift libraries in a Frameworks folder, which makes them invalid for App Store submission (ITMS-90206). Can we get an updated release that strips them back out, as seen in 6.0.4?

Submitting this here as there doesn't otherwise seem to be an easy way to submit issues for the framework.

**Comment by wayneburkett** [comment]
@jshier Thanks for bringing this to our attention. I'm going to run some tests on our end, but it looks like we'll need to make an update and target this for an upcoming release. Thanks!

**Comment by wayneburkett** [comment]
@jshier Our latest release ([iOS SDK 6.0.6](https://developer.foresee.com/docs/foresee-ios-sdk)) contains changes that should address this issue. Let me know if you run into any additional problems!
